# Change these first
owner: whytspace
repo: upptime

assignees:
  - whytspace

sites:
  - name: Übersicht 🇩🇪 (de)
    url: https://holiday-lescala.com/haeuser/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
    
  - name: Übersicht 🇬🇧 (en)
    url: https://holiday-lescala.com/en/homes/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"

  - name: Übersicht 🇫🇷 (fr)
    url: https://holiday-lescala.com/fr/maisons/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"

  - name: Übersicht 🇪🇸 (es)
    url: https://holiday-lescala.com/es/casas/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"



  - name: Bianya 🇩🇪 (de)
    url: https://holiday-lescala.com/h/haus-bianya/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
 
  - name: Bianya 🇬🇧 (en)
    url: https://holiday-lescala.com/en/h/house-bianya/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
         
  - name: Bianya 🇫🇷 (fr)
    url: https://holiday-lescala.com/fr/h/maison-bianya/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
     
  - name: Bianya 🇪🇸 (es)
    url: https://holiday-lescala.com/es/h/casa-bianya/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"



  - name: Girasol 🇩🇪 (de)
    url: https://holiday-lescala.com/h/haus-girasol/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"

  - name: Girasol 🇬🇧 (en)
    url: https://holiday-lescala.com/en/h/house-girasol/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"

  - name: Girasol 🇫🇷 (fr)
    url: https://holiday-lescala.com/fr/h/maison-girasol/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"

  - name: Girasol 🇪🇸 (es)
    url: https://holiday-lescala.com/es/h/casa-girasol/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"



  - name: Olives 🇩🇪 (de)
    url: https://holiday-lescala.com/h/haus-olives/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"

  - name: Olives 🇬🇧 (en)
    url: https://holiday-lescala.com/en/h/house-olives/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
    
  - name: Olives 🇫🇷 (fr)
    url: https://holiday-lescala.com/fr/h/maison-olives/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
    
  - name: Olives 🇪🇸 (es)
    url: https://holiday-lescala.com/es/h/casa-olives/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"



  - name: Francoli 🇩🇪 (de)
    url: https://holiday-lescala.com/h/haus-francoli/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"

  - name: Francoli 🇬🇧 (en)
    url: https://holiday-lescala.com/en/h/house-francoli/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
    
  - name: Francoli 🇫🇷 (fr)
    url: https://holiday-lescala.com/fr/h/maison-francoli/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
    
  - name: Francoli 🇪🇸 (es)
    url: https://holiday-lescala.com/es/h/casa-francoli/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"



  - name: Terany 🇩🇪 (de)
    url: https://holiday-lescala.com/h/haus-terany/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
    
  - name: Terany 🇬🇧 (en)
    url: https://holiday-lescala.com/en/h/house-terany/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"

  - name: Terany 🇫🇷 (fr)
    url: https://holiday-lescala.com/fr/h/maison-terany/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
    
  - name: Terany 🇪🇸 (es)
    url: https://holiday-lescala.com/es/h/casa-terany/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"



  - name: Roca 🇩🇪 (de)
    url: https://holiday-lescala.com/h/haus-roca/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"

  - name: Roca 🇬🇧 (en)
    url: https://holiday-lescala.com/en/h/house-roca/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
    
  - name: Roca 🇫🇷 (fr)
    url: https://holiday-lescala.com/fr/h/maison-roca/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
    
  - name: Roca 🇪🇸 (es)
    url: https://holiday-lescala.com/es/h/casa-roca/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"



  - name: Ancora 🇩🇪 (de)
    url: https://holiday-lescala.com/h/haus-ancora/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"

  - name: Ancora 🇬🇧 (en)
    url: https://holiday-lescala.com/en/h/house-ancora/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
    
  - name: Ancora 🇫🇷 (fr)
    url: https://holiday-lescala.com/fr/h/maison-ancora/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
    
  - name: Ancora 🇪🇸 (es)
    url: https://holiday-lescala.com/es/h/casa-ancora/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"



  - name: Can Llop 🇩🇪 (de)
    url: https://holiday-lescala.com/h/haus-can-llop/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
    
  - name: Can Llop 🇬🇧 (en)
    url: https://holiday-lescala.com/en/h/house-can-llop/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
    
  - name: Can Llop 🇫🇷 (fr)
    url: https://holiday-lescala.com/fr/h/maison-can-llop/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
    
  - name: Can Llop 🇪🇸 (es)
    url: https://holiday-lescala.com/es/h/casa-can-llop/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"



  - name: El Gall 🇩🇪 (de)
    url: https://holiday-lescala.com/h/haus-el-gall/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
    
  - name: El Gall 🇬🇧 (en)
    url: https://holiday-lescala.com/en/h/house-el-gall/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
    
  - name: El Gall 🇫🇷 (fr)
    url: https://holiday-lescala.com/fr/h/maison-el-gall/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
    
  - name: El Gall 🇪🇸 (es)
    url: https://holiday-lescala.com/es/h/casa-el-gall/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"



  - name: Medinya 🇩🇪 (de)
    url: https://holiday-lescala.com/h/haus-medinya/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
    
  - name: Medinya 🇬🇧 (en)
    url: https://holiday-lescala.com/en/h/house-medinya/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"    
    
  - name: Medinya 🇫🇷 (fr)
    url: https://holiday-lescala.com/fr/h/maison-medinya/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
    
  - name: Medinya 🇪🇸 (es)
    url: https://holiday-lescala.com/es/h/casa-medinya/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"



  - name: Le Coq 🇩🇪 (de)
    url: https://holiday-lescala.com/h/haus-le-coq/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
    
  - name: Le Coq 🇬🇧 (en)
    url: https://holiday-lescala.com/en/h/house-le-coq/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"    
    
  - name: Le Coq 🇫🇷 (fr)
    url: https://holiday-lescala.com/fr/h/maison-le-coq/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
    
  - name: Le Coq 🇪🇸 (es)
    url: https://holiday-lescala.com/es/h/casa-le-coq/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"



  - name: Dorna 🇩🇪 (de)
    url: https://holiday-lescala.com/h/haus-dorna/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
    
  - name: Dorna 🇬🇧 (en)
    url: https://holiday-lescala.com/en/h/house-dorna/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"    
    
  - name: Dorna 🇫🇷 (fr)
    url: https://holiday-lescala.com/fr/h/maison-dorna/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"
    
  - name: Dorna 🇪🇸 (es)
    url: https://holiday-lescala.com/es/h/casa-dorna/
    method: GET
    __dangerous__body_down_if_text_missing: "https://www.webplanner.de/tools/?"


    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Whytspace's Upptime
  introTitle: "Monitoring Websites via **Upptime**, the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from the [GitHub repository](https://github.com/whytspace/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
